# Generated by Django 3.0.6 on 2020-05-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.FloatField(default=0.0)),
                ('endTime', models.FloatField(default=0.0)),
                ('roomNum', models.IntegerField(default=5)),
                ('serveUnitNum', models.IntegerField(default=5)),
                ('Mode', models.IntegerField(default=1)),
                ('tempLimitHigh', models.IntegerField(default=32)),
                ('tempLimitLow', models.IntegerField(default=18)),
                ('defaultTargetTemp', models.IntegerField(default=26)),
                ('feeRateH', models.FloatField(default=2.0)),
                ('feeRateM', models.FloatField(default=1.5)),
                ('feeRateL', models.FloatField(default=1.0)),
                ('isSchedulerRunning', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverID', models.IntegerField()),
                ('roomID', models.IntegerField()),
                ('requestID', models.IntegerField()),
                ('startTime', models.FloatField(default=0.0)),
                ('endTime', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'SchedulerLog',
            },
        ),
        migrations.CreateModel(
            name='ServerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('state', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'ServerUnit',
            },
        ),
        migrations.CreateModel(
            name='WaitQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=-1)),
                ('roomID', models.IntegerField()),
            ],
            options={
                'db_table': 'WaitQueue',
            },
        ),
    ]
