# Generated by Django 3.0.6 on 2020-05-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='serveUnitNum',
            field=models.IntegerField(default=3),
        ),
    ]
