# Generated by Django 3.0.6 on 2020-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20200530_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='oneServeTime',
            field=models.IntegerField(default=15),
        ),
    ]
