# Generated by Django 3.0.6 on 2020-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0003_hotel_oneservetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='feeRateH',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='feeRateM',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='defaultTargetTemp',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tempLimitHigh',
            field=models.IntegerField(default=28),
        ),
    ]
