# Generated by Django 3.0.6 on 2020-06-01 12:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0.0)),
                ('roomID', models.IntegerField(default=0)),
                ('timeIn', models.FloatField(default=0.0)),
                ('timeOut', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('isPrint', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='RDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0.0)),
                ('roomID', models.IntegerField(default=0)),
                ('timeIn', models.FloatField(default=0.0)),
                ('timeOut', models.FloatField(default=0.0)),
                ('position', models.CharField(max_length=100)),
                ('isPrint', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'RDR',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
