# Generated by Django 3.0.6 on 2020-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.IntegerField()),
                ('time', models.FloatField(default=0.0)),
                ('temp', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('speed', models.IntegerField(default=1)),
                ('targetTemp', models.FloatField(default=26)),
            ],
            options={
                'db_table': 'RoomRequest',
            },
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomID', models.IntegerField()),
                ('time', models.FloatField(default=0.0)),
                ('temp', models.FloatField(default=0.0)),
                ('fee', models.FloatField(default=0.0)),
                ('state', models.IntegerField(default=0)),
                ('plus', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'RoomState',
            },
        ),
    ]
