# Generated by Django 3.0.6 on 2020-05-30 17:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=0.0)),
                ('roomList', models.CharField(blank=True, default='', max_length=10, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('type', models.IntegerField(default=1)),
                ('date', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Report',
            },
        ),
    ]
